demo/demo/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from prometheus_client import generate_latest
from django.http import HttpResponse


def metrics(request):
    # Prometheus scrape endpointi için metrikleri döndürme
    return HttpResponse(generate_latest(), content_type='text/plain')

urlpatterns = [
    path('', views.index),
    path('todo/', include('todo.urls')),
    path('user/', include("users.urls")),
    path('metrics/', metrics, name='metrics'),
    path('prometheus/', include('django_prometheus.urls')),
    path('index/', views.index),
    path('admin/', admin.site.urls),
    
]

demo/todo/urls.py
from django.urls import path
from .views import TodoList, TodoCreate, TodoSearch, TodoDetail, TodoUpdate, TodoDelete


app_name = 'todo'

urlpatterns = [

    path('', TodoList.as_view(), name='todo_list'),
    path('create/', TodoCreate.as_view(), name='todo_create'),
    path('search/', TodoSearch.as_view(), name='todo_search'),
    path('<slug:slug>/<int:pk>/', TodoDetail.as_view(), name='todo_detail'),
    path('<slug:slug>/<int:id>/update/', TodoUpdate.as_view(), name='todo_update'),
    path('<slug:slug>/<int:pk>/delete/', TodoDelete.as_view(), name='todo_delete'),
    
]

demo/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/',views.register_user,name='register_user'),
    path('dashboard/',views.dashboard,name='dashboard'),
    
]
    

demo/todo/models.py
from datetime import timezone
from django.db import models
from django.shortcuts import redirect
from django.utils.text import slugify
from django.urls import reverse


class TodoItem(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    completed = models.BooleanField(default=False)
    is_archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('todo_detail', kwargs={'slug': self.slug, 'pk': self.id})

    def update(self, completed, *args, **kwargs):
        self.completed = completed
        self.updated_at = timezone.now()
        self.save(*args, **kwargs)
        return redirect(self.get_absolute_url())

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.title

demo/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import TodoItem
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.utils import timezone
from prometheus_client import Counter
from django.http import HttpResponse
from django.template import loader

# Counter metriği oluşturma
todo_request_total = Counter('todo_requests_total', 'Total number of todo requests')
todo_request_create = Counter('todo_create_requests_total', 'Total number of todo requests created')
todo_request_update= Counter('todo_update_requests_total', 'Total number of todo requests update')
todo_request_delete = Counter('todo_delete_requests_total', 'Total number of todo requests delete')
todo_request_detail = Counter('todo_detail_requests_total', 'Total number of todo requests detail')



class TodoList(ListView):
    
    model = TodoItem
    template_name = 'todo_list.html'
    context_object_name = 'todos'

    def get(self, request, *args, **kwargs):
        todo_request_total.inc()
        return super().get(request, *args, **kwargs)
    
    
    def post(self, request, *args, **kwargs):
        todo_request_total.inc()
        return super().post(request, *args, **kwargs)


class TodoCreate(CreateView):  # CreateView sınıfından TodoCreate adında bir sınıf oluşturuyoruz
    model = TodoItem # model.py deki TodoItem modelini kullanıyoruz
    template_name = 'todo_create.html' # template dosyamızı belirtiyoruz
    fields = ['title','completed','is_archived'] # formda göstermek istediğimiz alanları belirtiyoruz
    success_url = reverse_lazy('todo:todo_list') # formu başarıyla doldurduktan sonra yönlendirileceğimiz url i belirtiyoruz


    def form_valid(self, form): # formu doğruladıktan sonra çalışacak fonksiyonu belirtiyoruz
        title = form.cleaned_data['title'] # formdan title alanını alıyoruz
        slug = slugify(title) # title alanını sluga çeviriyoruz
        # Slug alanını benzersiz hale getirmek için döngü kullanarak kontrol ediyoruz
        i = 1 # döngü için i değerini 1 olarak belirliyoruz
        while TodoItem.objects.filter(slug=slug).exists(): # eğer slug alanı veritabanında varsa
            slug = slugify(title) + '-' + str(i) # slug alanını tekrar sluga çevirip i değerini ekliyoruz
            i += 1 # i değerini 1 arttırıyoruz
        form.instance.slug = slug # formun slug alanına slug değerini atıyoruz  
        return super().form_valid(form) # formu doğruluyoruz
    
    def get(self, request, *args, **kwargs):
        todo_request_create.inc()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        todo_request_create.inc()
        return super().post(request, *args, **kwargs)


class TodoUpdate(UpdateView):
    model = TodoItem
    template_name = 'todo_update.html'
    fields = ['title', 'completed', 'is_archived']
    context_object_name = 'todo'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'id'


    def get_object(self, queryset=None): 
        slug = self.kwargs.get('slug') # urldeki slug alanını alıyoruz
        id = self.kwargs.get('id') # urldeki id alanını alıyoruz
        return get_object_or_404(TodoItem, slug=slug, id=id) # TodoItem modelinden slug ve id alanlarına göre nesne alıyoruz

    def get_success_url(self):
        return reverse_lazy('todo:todo_detail', kwargs={'slug': self.object.slug, 'pk': self.object.pk}) # formu başarıyla doldurduktan sonra yönlendirileceğimiz url i belirtiyoruz

    def form_valid(self, form):
        self.object = form.save(commit=False) # formu kaydetmeden önce object değişkenine atıyoruz
        self.object.updated_at = timezone.now() # object değişkeninin updated_at alanına şu anki zamanı atıyoruz
        self.object.save() # object değişkenini kaydediyoruz
        return redirect('todo:todo_detail', slug=self.object.slug, pk=self.object.pk) # formu başarıyla doldurduktan sonra yönlendirileceğimiz url i belirtiyoruz

    def get_initial(self):
        initial = super().get_initial() # get_initial fonksiyonunu çağırıyoruz çünkü formun title alanına todo.title değerini atayacağız
        todo = self.get_object() # get_object fonksiyonunu çağırıyoruz çünkü formun completed alanına todo.completed değerini atayacağız
        initial['title'] = todo.title
        initial['completed'] = todo.completed # formun completed alanına todo.completed değerini atıyoruz
        initial['is_archived'] = todo.is_archived # formun is_archived alanına todo.is_archived değerini atıyoruz
        return initial
    
    def get(self, request, *args, **kwargs):
        todo_request_update.inc()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        todo_request_update.inc()
        return super().post(request, *args, **kwargs)

  



class TodoDetail(DetailView):
    model = TodoItem
    template_name = 'todo_detail.html'
    context_object_name = 'todo'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_data = request.POST
        
        return redirect('todo:todo_update', slug=self.object.slug, pk=self.object.pk)

    def get(self, request, *args, **kwargs):
        todo_request_detail.inc()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        todo_request_detail.inc()
        return super().post(request, *args, **kwargs)
     

class TodoDelete(DeleteView):
    model = TodoItem
    template_name = 'todo_delete.html'
    context_object_name = 'todo'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('todo:todo_list')

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        pk = self.kwargs.get('pk')
        if slug and pk:
            queryset = self.get_queryset().filter(slug=slugify(slug), pk=pk)
        elif slug:
            queryset = self.get_queryset().filter(slug=slugify(slug))
        elif pk:
            queryset = self.get_queryset().filter(pk=pk)
        else:
            queryset = self.get_queryset()
        return get_object_or_404(queryset)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.success_url)
    
    
    def get(self, request, *args, **kwargs):
            todo_request_delete.inc()
            return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        todo_request_delete.inc()
        return super().post(request, *args, **kwargs)

    
class TodoSearch(View):
    def get(self, request):
        query = request.GET.get('q')
        todos = TodoItem.objects.filter(title__icontains=query)
        return render(request, 'todo_search.html', {'todos': todos})

demo/todo/templates/todo_archive.html
<!DOCTYPE html>
<html>
<head>
    <title>ToDo Archive</title>
</head>
<body>
    <h1>ToDo Archive</h1>
    <h2>{{ todo.id }}</h2>
    <h2>{{ todo.title }}</h2>
    <p>Completed: {{ todo.completed }}</p>
    <p>Created At: {{ todo.created_at }}</p>
    <p>Updated At: {{ todo.updated_at }}</p>
    <p><a href="/">index</a></p>
    {% if is_archived %}
        <p>Archived: Yes</p>
        <a href="{% url 'todo:todo_unarchive' slug=todo.slug pk=todo.pk %}">Unarchive</a>
    {% else %}
        <p>Archived: No</p>
        <a href="{% url 'todo:todo_archive' slug=todo.slug pk=todo.pk %}">Archive</a>
    {% endif %}
</body>
</html>

demo/todo/templates/todo_create.html
<!DOCTYPE html>
<html>
<head>
    <title>Create User</title>
</head>
<body>
    <h1>Create User</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        {{form.errors}}
        
        <button type="submit">Create</button>
    </form>
</body>
</html>

demo/todo/templates/todo_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete ToDo Item</title>
</head>
<body>
    <h1>Delete ToDo Item</h1>
    <p>Are you sure you want to delete "{{ todo.title }}"?</p>
    <form method="post" action="{% url 'todo:todo_delete' slug=todo.slug pk=todo.pk %}">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <a href="{% url 'todo:todo_detail' slug=todo.slug pk=todo.pk %}">Cancel</a>
    </form>
</body>
</html>

demo/todo/templates/todo_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>ToDo Detail</title>
</head>
<body>
    <h1>ToDo Detail</h1>
    <h2>id: {{ todo.id }}</h2>
    <h2>title: {{ todo.title }}</h2>
    <h2>Tamamlama: {{ todo.completed }}</h2>
    <h2>Slug: {{ todo.slug }}</h2>
    <h2>Created: {{ todo.created_at }}</h2>
    <h2>Update: {{ todo.updated_at }}</h2>
    <h2>Arşiv Durumu: {{ todo.is_archived }}</h2>

    <form method="post" action="{% url 'todo:todo_update' slug=todo.slug id=todo.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" onclick="setActionUrl()">Güncelle</button>
        <button type="submit"><a href="{% url 'todo:todo_detail' slug=todo.slug pk=todo.pk %}">Detail</a></button>
        <button><a href="{% url 'todo:todo_delete' slug=todo.slug pk=todo.pk %}">Sil</a></button>
        <button><a href="{% url 'todo:todo_list' %}">List</a></button>


    </form>


    <script>
        function setActionUrl() {
            var form = document.querySelector('form');
            var actionUrl = form.getAttribute('action');
            var slug = "{{ todo.slug }}";
            var id = "{{ todo.pk }}";
            var updatedActionUrl = actionUrl.replace('slug', slug).replace('id', id);
            form.setAttribute('action', updatedActionUrl);
        }
    </script>

</body>
</html>

demo/todo/templates/todo_list.html
<!DOCTYPE html>
<html>
<head>
    <title>ToDo List</title>
</head>
<body>
    <h1>ToDo List</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Archived</th>
                <th>Completed</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
                <tr>
                    <td>{{ todo.id }}</td>
                    <td><a href="{% url 'todo:todo_detail' slug=todo.slug pk=todo.pk %}">{{ todo.title }}</a></td>
                    <td>{% if todo.is_archived %}Yes{% else %}No{% endif %}</td>
                    <td>{% if todo.completed %}Yes{% else %}No{% endif %}</td>
                    <td>
                        <form method="post" action="{% url 'todo:todo_update' slug=todo.slug id=todo.pk %}">
                            {% csrf_token %}
                            <button type="submit" onclick="setActionUrl('{{ todo.slug }}', '{{ todo.pk }}','{{ todo.completed }}', '{{ todo.isArchived }}')">Güncelle</button>
                        </form>
                        <a href="{% url 'todo:todo_detail' slug=todo.slug pk=todo.pk %}">Detail</a> |
                        <a href="{% url 'todo:todo_delete' slug=todo.slug pk=todo.pk %}">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">No ToDo items found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Create ToDo Item</h2>
    <form method="post" action="{% url 'todo:todo_create' %}">
        {% csrf_token %}
    
        <div>
            <label for="id_title">Title:</label>
            <input type="text" name="title" id="id_title">
        </div>
    
        <div>
            <label for="id_completed">Completed:</label>
            <input type="checkbox" name="completed" id="id_completed">
        </div>
    
        <button type="submit">Oluştur</button>
        <a href="{% url 'users:register_user' %}">Kayıt Ol</a>
        <a href="{% url 'users:login' %}">Giriş</a>


    </form>

    
    <script>
        function setActionUrl() {
            var form = document.querySelector('form');
            var actionUrl = form.getAttribute('action');
            var slug = "{{ todo.slug }}";
            var id = "{{ todo.pk }}";
            var completed = "{{ todo.completed }}";
            var isArchived = "{{ todo.is_archived }}";
            var updatedActionUrl = actionUrl.replace('slug', slug).replace('id', id).replace('completed', completed).replace('is_archived', isArchived);
            form.setAttribute('action', updatedActionUrl);
        }
    </script>
    
</body>
</html>

demo/todo/templates/todo_search.html
<!DOCTYPE html>
<html>
<head>
    <title>Todo Search</title>
</head>
<body>
    <h1>Todo Search</h1>
    <form method="GET">
        <input type="text" name="q" placeholder="Search Todo">
        <button type="submit">Search</button>
    </form>

    {% if todos %}
        <h2>Search Results:</h2>
        <ul>
            {% for todo in todos %}
                <li>{{ todo.title }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p>
    {% endif %}
</body>
</html>

demo/todo/templates/todo_update.html
<!DOCTYPE html>
<html>
<head>
    <title>Update ToDo Item</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $( function() {
            $( "#created_at" ).datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true
            });
        } );
    </script>
</head>
<body>
    <h1>Update ToDo Item</h1>
    <form method="post" action="{% url 'todo:todo_update' slug=todo.slug id=todo.pk %}">
        {% csrf_token %}
    
        <div class="form-group">
            <label for="id_title">Title:</label>
            <input type="text" id="id_title" name="title" value="{{ form.initial.title }}">
        </div>
    
        <div class="form-group">
            <label for="id_completed">Completed:</label>
            <input type="checkbox" id="id_completed" name="completed" {% if form.initial.completed %}checked{% endif %}>
        </div>
        
        <div class="form-group">
            <label for="id_is_archived">Is Archived:</label>
            <input type="checkbox" id="id_is_archived" name="is_archived" {% if form.initial.is_archived %}checked{% endif %}>
        </div>
        
        <div class="form-group">
            <label for="id_created_at">Created At:</label>
            <input type="text" id="id_created_at" name="created_at" value="{{ todo.created_at|date:'Y-m-d' }}" readonly>
        </div>
    
        <div class="form-group">
            <label for="id_updated_at">Updated At:</label>
            <input type="text" id="id_updated_at" name="updated_at" value="{{ todo.updated_at|date:'Y-m-d' }}" readonly>
        </div>
    
        <div class="button-group">
            <button type="submit" class="btn btn-primary">Güncelle</button>
            <a href="{% url 'todo:todo_detail' slug=todo.slug pk=todo.pk %}" class="btn btn-secondary">Detail</a>
            <button class="btn btn-danger"><a href="{% url 'todo:todo_delete' slug=todo.slug pk=todo.pk %}">Sil</a></button>
            <button class="btn btn-primary"><a href="{% url 'todo:todo_list' %}">List</a></button>
        </div>
    </form>
    
</body>
</html>